### PR TITLE
Allow multiple global script objects

### PR DESCRIPTION
**Pull request by j-o**
See cginternals/cppexpose#45.

### CODE REVIEW

**Comment by sbusch42** [comment]
When I start gloperate-viewer, I get the following error message:

file:///workspace/projects/cginternals/gloperate/data/gloperate/qml/Viewer.qml:431: ReferenceError: gloperate is not defined

I'm using Qt 5.4. Is this different on Qt 5.7/8/9, or didn't you check gloperate-viewer?

**Comment by j-o** [comment]
I tested with gloperate-viewer and I don't get this error using Qt 5.9 (just some others that occurred before). Will test Qt 5.4.

**Comment by sbusch42** [comment]
It seems to work with Qt 5.9. But I didn't find any changelog mentioning this change, so it could very well stop working in the next version. According to the Qt documentation, the global object in a QML context, is as I said, read-only. See here (in Note):

http://doc.qt.io/qt-5/qtqml-javascript-qmlglobalobject.html

**Comment by j-o** [comment]
Alright, here is another approach using `QQmlContext::setContextProperty`. I can't test this with Qt 5.4 because it crashes with a corrupted stack when trying to load the viewer.qml (Qt 5.4 with Visual Studio 2013 Win64 on Windows 10).

Incidentally, how serious are about still supporting Visual Studio 2013? Because cppassist & gloperate don't compile.

**Comment by sbusch42** [comment]
Thank you, this seems to work :) I don't remember why I dismissed this approach when I implemented this, somehow it didn't work then. It should be noted that this approach also has one disadvantage, being that scripts executed just in the QJSEngine are not able to access the global objects. Therefore, everything has to be executed via QQmlExpression. But we are already doing that (see QmlScriptContext::evaluate).

**Pull request merged**
