### PR TITLE
Add continuous redraw

### PR DESCRIPTION
**Pull request by scheibel**
For me, this is currently a workaround for a strange-to-debug pipeline setup, but I think this may be a useful feature in general.

### CODE REVIEW

**Comment by sbusch42** [comment]
That kind of defeats the purpose of the entire pipeline setup. For me it works, if you want continuous redraw, see to it that "rendered" is invalidated on update (connect it to the timeDelta input somehow).
If we do this correctly, I find it better to use than to have a global switch like that.

**Comment by sbusch42** [comment]
There is currently a bug in RasterizationStage (it doesn't set rendered to true) which screws up this logic. I have not yet commited this because I'm waiting for the other pull requests to get merged before throwing in more changes. Apart from that the logic seems to work for me.

**Comment by scheibel** [comment]
Yeah, updating the rasterization stage outputs after rendering fixes this error for me, too.
Unfortunately, this stage was the only one I missed while searching for this exact defect.

**Comment by sbusch42** [comment]
can we close this?

**Comment by scheibel** [comment]
Yes.

**Pull request closed without merging**
