### PR TITLE
Create new threading-aware canvas class

### PR DESCRIPTION
**Pull request by sbusch42**
Lets refactor the canvas and mainloop here. It should be clearly designed and documented what methods and signals are to be used from what thread (UI thread or render thread) to make the new canvas class work on multithreaded viewers such as QtQuick.

### CODE REVIEW

**Comment by sbusch42** [comment]
Please test this on all platforms and give feedback to the new rendering and mainloop implementations

**Comment by sbusch42** [comment]
Works on macOS

**Comment by sbusch42** [comment]
Works on Windows

**Comment by sbusch42** [comment]
Last call for feedback on this PR :)

**Comment by scheibel** [comment]
From what I can see, the new ```Canvas``` handles virtual time updates internally. However, using the video exporter (e.g., ffmpeg video export), the virtual time is handled by the exporter. I suggest we re-add an interface to handle virtual time externally.

**Comment by Tobias1595** [comment]
Right after startup the following error appears exactly 6 times on cerr:
`#fatal: error: 0x500, high severity (API)`
`GL_INVALID_ENUM error generated. <pname> requires feature(s) disabled in the current profile.`
After some searching, I found that these errors are produced by GLContextUtils::retrieveFormat().

It seems that GL_RED_BITS through GL_STENCIL_BITS are not part of the OpenGL 4.5 specification anymore (see lists in [4.5 glGet reference](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGet.xhtml) and [2.1 glGet reference](https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glGet.xml))

Yet I haven't noticed any negative impact whatsoever though, but I also don't know, where these values are required at the moment. Neither do I know, why the very same code on the master branch runs without generating the error messages.

**Comment by sbusch42** [comment]
Thanks for reporting that. Please make a separate issue, we should investigate it further.

**Pull request merged**
