### PR TITLE
Property editor

### PR DESCRIPTION
**Pull request by sbusch42**
First prototype for a property editor and examples for generic (gloperate-viewer) and specialized (gloperate-qtquick-example) UIs

### CODE REVIEW

**Comment by j-o** [comment]
Produces errors (Visual Studio 2015 Update 3, Qt 5.7):
```
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/ValueEdit.qml:17: TypeError: Cannot read property 'implicitHeight' of null
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/ValueEdit.qml:16: TypeError: Cannot read property 'implicitWidth' of null
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/ValueEdit.qml:17: TypeError: Cannot read property 'implicitHeight' of null
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/ValueEdit.qml:16: TypeError: Cannot read property 'implicitWidth' of null
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/ValueEdit.qml:17: TypeError: Cannot read property 'implicitHeight' of null
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/ValueEdit.qml:16: TypeError: Cannot read property 'implicitWidth' of null
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/ValueEdit.qml:17: TypeError: Cannot read property 'implicitHeight' of null
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/ValueEdit.qml:16: TypeError: Cannot read property 'implicitWidth' of null
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/ValueEdit.qml:17: TypeError: Cannot read property 'implicitHeight' of null
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/ValueEdit.qml:16: TypeError: Cannot read property 'implicitWidth' of null
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/ValueEdit.qml:17: TypeError: Cannot read property 'implicitHeight' of null
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/ValueEdit.qml:16: TypeError: Cannot read property 'implicitWidth' of null
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/ValueEdit.qml:17: TypeError: Cannot read property 'implicitHeight' of null
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/ValueEdit.qml:16: TypeError: Cannot read property 'implicitWidth' of null
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/ValueEdit.qml:17: TypeError: Cannot read property 'implicitHeight' of null
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/ValueEdit.qml:16: TypeError: Cannot read property 'implicitWidth' of null
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/ValueEdit.qml:17: TypeError: Cannot read property 'implicitHeight' of null
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/ValueEdit.qml:16: TypeError: Cannot read property 'implicitWidth' of null
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/PropertyEditor.qml:41:23: Unable to assign [undefined] to QString
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/PropertyEditor.qml:41:23: Unable to assign [undefined] to QString
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/PropertyEditor.qml:41:23: Unable to assign [undefined] to QString
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/PropertyEditor.qml:41:23: Unable to assign [undefined] to QString
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/PropertyEditor.qml:41:23: Unable to assign [undefined] to QString
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/PropertyEditor.qml:41:23: Unable to assign [undefined] to QString
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/PropertyEditor.qml:41:23: Unable to assign [undefined] to QString
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/PropertyEditor.qml:41:23: Unable to assign [undefined] to QString
file:///D:/projects/gloperate/data/gloperate/qml/PropertyEditor/PropertyEditor.qml:41:23: Unable to assign [undefined] to QString
```

Using gloperate-viewer, only the `angle` and `rotate` properties seem to work.
Viewports display `(0, 0, 0, 0)`, changing the backgroundColor has no effect and trying to load another texture results in the fallback texture being displayed.

**Comment by sbusch42** [comment]
The other properties beside angle, rotate, and texture are not supposed to work because they are automatically connected by the window (e.g., viewport, target FBO etc.). Today we discussed ways to hide such automatic properties from the UI.

Changing the texture should work, though. Please debug what filename is passed on to the stage (I would guess the filename may get mangled up maybe because of Windows specifica).

**Comment by sbusch42** [comment]
Merging now to have a starting point for development on the pipeline editor

**Comment by j-o** [comment]
Yep, there is s slash in front that should not be there: `"/C:/Users/Jole/Desktop/tsas-front.png"`

**Pull request merged**
