### PR TITLE
Offscreen context

### PR DESCRIPTION
**Pull request by j-o**
This PR provides basic integration of offscreen contexts based on the [glheadless](https://github.com/j-o/glheadless) library.
There are two examples demonstrating the use:
- `gloperate-glheadless-example` creates an offscreen context and then drops to a console (no window)
- `gloperate-qt-glheadless-example` uses an offscreen context to generate a texture that is then used on the main context created with Qt

### CODE REVIEW

**Comment by j-o** [comment]
Based on #181

**Comment by scheibel** [comment]
This PR depends on glheadless and adds this library as (optional) dependency to gloperate.
You state that glheadless requires a C++14 enabled compiler. Is your library compilable with any other the following compilers:
* GCC 4.8 and higher
* MSVC 2013 Update 3 (maybe Update 5 can be expected by now?) or higher
* Clang 3.5 and higher
* AppleClang 6 and higher

**Comment by scheibel** [comment]
Is it intended that a compiled glheadless library may be incompatible with a gloperate library?
I think there is the assumption that context hijacking operates on contexts created with a specific window API.
I have no experience with, e.g., EGL as window API to manipulate or use OpenGL contexts created with Qt (with usually used GLX on Linux systems).

**Comment by j-o** [comment]
Required compiler support has been lowered to C++11. The library successfully compiles with the compilers you mentioned, except I was unable to obtain a working installer for VS2013 Update 3, so I tested with Update 5.

The EGL option is now a strictly obeyed CMake switch (off by default).
If I understood correctly, adding EGL support to glbinding faces the same problem of detecting the context API used to create a context. I suggest leaving this a compile-time decision in glheadless for now and apply any run-time detection solution found in the context of glbinding to glheadless as well.
I think this should resolve the compatibility concerns you raised for now.

**Pull request closed without merging**
