### PR TITLE
Integrate new UI

### PR DESCRIPTION
**Pull request by sbusch42**
Please test this on as many platforms as possible. Also, there are two different implementations for Qt 5.4 and Qt >= 5.7, both need to be tested.

### CODE REVIEW

**Comment by sbusch42** [comment]
My tests so far:
- Linux works (Qt 5.5)
- Windows does not work, UI is displayed but no gloperate rendering is visible (no idea why)
- Mac does not work (OpenGL 2.1 context is created, the context version must be set somewhere. Look at Qt::AA_UseDesktopOpenGL).

Please help me fix this.

**Comment by scheibel** [comment]
I added some fixes for Ubuntu that are required for my setup (Ubuntu 16.04, Qt 5.5.1):
1. Fix resize crashes and optimize / reevaluate Qt framebuffer reconfiguration upon resize
2. Start integrating a pipeline deinitialization before OpenGL context destruction upon application deinitialization

**Comment by j-o** [comment]
- Text on buttons looks horrible (compare with window bar) using Windows 10, Qt 5.7, no HDPI

gloperate-viewer

**Comment by j-o** [comment]
- Read access violation when closing app:
```
>	globjectsd.dll!globjects::IDTrait::id() Line 67	C++
 	globjectsd.dll!globjects::Object::id() Line 50	C++
 	globjectsd.dll!globjects::Program::detach(globjects::Shader * shader) Line 144	C++
 	globjectsd.dll!globjects::Program::~Program() Line 75	C++
 	gloperate-qtquickd.dll!globjects::Program::`scalar deleting destructor'(unsigned int)	C++
 	gloperate-qtquickd.dll!std::default_delete<globjects::Program>::operator()(globjects::Program * _Ptr) Line 1608	C++
 	gloperate-qtquickd.dll!std::unique_ptr<globjects::Program,std::default_delete<globjects::Program> >::~unique_ptr<globjects::Program,std::default_delete<globjects::Program> >() Line 1820	C++
 	gloperate-qtquickd.dll!gloperate_qtquick::RenderItemRenderer::~RenderItemRenderer() Line 41	C++
 	gloperate-qtquickd.dll!gloperate_qtquick::RenderItemRenderer::`vector deleting destructor'(unsigned int)	C++
 	Qt5Quickd.dll!QSGFramebufferObjectNode::~QSGFramebufferObjectNode() Line 207	C++
 	Qt5Quickd.dll!QSGFramebufferObjectNode::`scalar deleting destructor'(unsigned int)	C++
 	Qt5Quickd.dll!QSGNode::destroy() Line 395	C++
 	Qt5Quickd.dll!QSGNode::~QSGNode() Line 327	C++
 	Qt5Quickd.dll!QSGTransformNode::~QSGTransformNode() Line 1177	C++
 	Qt5Quickd.dll!QSGTransformNode::`vector deleting destructor'(unsigned int)	C++
 	Qt5Quickd.dll!QQuickWindowPrivate::cleanupNodesOnShutdown(QQuickItem * item) Line 2808	C++
 	Qt5Quickd.dll!QQuickWindowPrivate::cleanupNodesOnShutdown(QQuickItem * item) Line 2835	C++
 	Qt5Quickd.dll!QQuickWindowPrivate::cleanupNodesOnShutdown(QQuickItem * item) Line 2835	C++
 	Qt5Quickd.dll!QQuickWindowPrivate::cleanupNodesOnShutdown(QQuickItem * item) Line 2835	C++
 	Qt5Quickd.dll!QQuickWindowPrivate::cleanupNodesOnShutdown(QQuickItem * item) Line 2835	C++
 	Qt5Quickd.dll!QQuickWindowPrivate::cleanupNodesOnShutdown(QQuickItem * item) Line 2835	C++
 	Qt5Quickd.dll!QQuickWindowPrivate::cleanupNodesOnShutdown(QQuickItem * item) Line 2835	C++
 	Qt5Quickd.dll!QQuickWindowPrivate::cleanupNodesOnShutdown(QQuickItem * item) Line 2835	C++
 	Qt5Quickd.dll!QQuickWindowPrivate::cleanupNodesOnShutdown(QQuickItem * item) Line 2835	C++
 	Qt5Quickd.dll!QQuickWindowPrivate::cleanupNodesOnShutdown(QQuickItem * item) Line 2835	C++
 	Qt5Quickd.dll!QQuickWindowPrivate::cleanupNodesOnShutdown(QQuickItem * item) Line 2835	C++
 	Qt5Quickd.dll!QQuickWindowPrivate::cleanupNodesOnShutdown() Line 2844	C++
 	Qt5Quickd.dll!QSGRenderThread::invalidateOpenGL(QQuickWindow * window, bool inDestructor, QOffscreenSurface * fallback) Line 494	C++
 	Qt5Quickd.dll!QSGRenderThread::event(QEvent * e) Line 400	C++
 	Qt5Quickd.dll!QSGRenderThread::processEventsAndWaitForMore() Line 692	C++
 	Qt5Quickd.dll!QSGRenderThread::run() Line 720	C++
 	Qt5Cored.dll!QThreadPrivate::start(void * arg) Line 393	C++
 	ucrtbased.dll!invoke_thread_procedure(unsigned int(*)(void *) procedure, void * const context) Line 92	C++
 	ucrtbased.dll!thread_start<unsigned int (__cdecl*)(void * __ptr64)>(void * const parameter) Line 115	C++
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown
```

**Comment by sbusch42** [comment]
Current status:
- Works on Linux
- Works on Windows
- Crashes on macOS (at least on my computer, we had it working on another device)

**Comment by sbusch42** [comment]
For me, it works on all three systems now :) Please confirm.
However, I still encounter crashes on shutdown.

**Comment by scheibel** [comment]
I think I found the error for the shutdown crashes. I have a solution, too.
I still have to figure out why the current implementation is erroneous and why my fix is required and how it changes the erroneous code.

**Comment by sbusch42** [comment]
Please test this again on Windows and macOS. I'm going to merge this soon (very soon ...)

**Pull request merged**
