### PR TITLE
Fix stage sorting not detecting loops

### PR DESCRIPTION
**Pull request by Tobias1595**

### CODE REVIEW

**Comment by scheibel** [comment]
Can you summerize the previous behavior, the proposed behavior and how the single-line change achieves this?

**Comment by Tobias1595** [comment]
The main intent of visiting a stage is to make sure that all other stages providing input for this stage are sorted in front of it. After a stage was visited, it can be appended to the sorting order. To exclude the already sorted stages from these checks, they are removed from ```stages```.
During a visit the stages left in ```stages``` are checked on connections to the visited stage. If the visited stage gets an input from any of these stages, that particular stage is recursively visited. After the recursion ends and the stage is inserted into the sorting order, the check is restarted with the remaining stages.
Because the end of a visit is followed by appending the visited stage to the sorting order, a stage should only be visited once. Visiting a stage twice means that the dependencies between some of the stages form a directed cycle and that very cycle was traversed by the recursion when visiting the stage a second time before its first visit could end. A directed cycle makes sorting the stages impossible and the algorithm is terminated.
Removing a stage from ```stages``` before visiting it causes all recursively following visit calls to ignore this stage while searching for dependencies, effectively treating it as already sorted. This makes finding directed cycles impossible. The last dependency closing a cycle could not be found because the providing stage is not contained in ```stages``` anymore.
Instead a stage should only be removed from ```stages``` directly before inserting it into the sorting order. This way it's clear that stages relevant for the mentioned checks can always be found in ```stages```.

**Comment by scheibel** [comment]
I recall that this PR provides a non-terminating algorithm instead of an actual solution by accident. @Tobias1595 can you confirm?

**Comment by sbusch42** [comment]
@scheibel Please review this.
all: please check if the same problem/fix also needs to be applied in gloperate 2.0

**Pull request merged**
